site_name: GenAPI
site_url: https://genapi.org
site_description: Easy API use for Generative AI apps
copyright: Copyright &copy; 2023 - present, Manav Sehgal – All rights reserved | <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.indexes
    # Vegalite not render if this is enabled
#    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    admonition:
      note: material/chat-processing-outline
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      list-creation: fontawesome/solid/list
      dataset-creation: fontawesome/solid/database
      chatgpt-model: fontawesome/solid/comments
      research-function: fontawesome/solid/brain
      education-industry: fontawesome/solid/graduation-cap
      image-generation: fontawesome/solid/image
      creative-function: material/creation
      film-industry: material/filmstrip
      midjourney-model: fontawesome/solid/eye
      engineering-function: fontawesome/solid/wrench
      software-industry: fontawesome/solid/laptop-code
      diagram-generation: fontawesome/solid/diagram-project
      knowledge-management: fontawesome/solid/brain
      consulting-industry: fontawesome/solid/handshake
      data-science: fontawesome/solid/atom
      hugging-face: fontawesome/solid/atom
      generative-ai: fontawesome/solid/brain
      openai: fontawesome/solid/brain
      chatgpt: fontawesome/solid/comments
      analytics-function: fontawesome/solid/chart-line

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - charts
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom  
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_file: tags.md
  - social:
      cards_font: Roboto
      cards_dir: images/social
      cards_color:
        fill: "#2E2E2E" 
        text: "#FFFFFF"
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
      
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manavsehgal/genmapp
      name: Genmapp on GitHub
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    List Creation: list-creation
    Dataset Creation: dataset-creation
    ChatGPT Model: chatgpt-model
    Research Function: research-function
    Education Industry: education-industry
    Image Generation: image-generation
    Film Industry: film-industry
    Creative Function: creative-function
    Midjourney Model: midjourney-model
    Engineering Function: engineering-function
    Software Industry: software-industry
    Diagram Generation: diagram-generation
    Knowledge Management: knowledge-management
    Consulting Industry: consulting-industry
    Data Science: data-science
    Hugging Face: hugging-face
    Generative AI: generative-ai
    OpenAI: openai
    ChatGPT: chatgpt
    Analytics Function: analytics-function

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

nav:
  - Home: index.md
  - Functions:
    - OpenAI Functions with Climate API: functions/openai-functions-with-climate-apis.md
